

import '../constants/constants.dart';

class Strings {
  static const String currency = '₹';
  static const String createAccount = 'Create Account';
  static const String uploadProfilePhoto = 'Upload Profile Photo';
  static const String yourFullName = 'Your Full Name';
  static const String name = 'Name';
  static const String birthdayDateHint = 'YYYY-MM-DD';
  static const String emailAddress = 'Email Address';
  static const String email = 'email';
  static const String enterAddress = 'Enter Address';
  static const String serviceType = 'Service Type';
  static const String liveStatus = 'Live Status';
  static const String onTask = 'On Task';
  static const String gender = 'Gender';
  static const String selectGender = 'Select Gender';
  static const String selectState = 'Select State';
  static const String selectCity = 'Select City';
  static const String searchState = 'Search State';
  static const String searchCity = 'Search City';
  static const String pleaseSelectStateFirst = 'Please select state first';
  static const String referralCode = 'Referral Code';
  static const String accountType = 'Account Type';
  static const String enterYourReferralCode = 'Enter Your Referral Code';
  static const String next = 'Next';
  static const String submit = 'Submit';
  static const String buy = 'Buy';
  static const String continue_ = 'Continue';
  static const String done = 'Done';
  static const String update = 'Update';
  static const String version = 'Version';
  static const String welcomeTo = 'Welcome To';
  static const String getOTP = 'Get OTP';
  static const String mobileNumber = 'Mobile Number';
  static const String number = 'number';
  static const String verify = 'Verify';
  static const String verificationCode = 'Verification Code';
  static const String weSentVerificationCodeOnYour = 'We have sent the verification code on your';
  static const String didNotReceiveCode = 'Didn’t Receive Code?';
  static const String resend = 'Resend';
  static const String home = 'Home';
  static const String offers = 'Offers';
  static const String beta24Id = 'Beta24 ID';
  static const String notification = 'Notification';

  //static const String booking = 'Booking';
  static const String profile = 'Profile';
  static const String myProfile = 'My Profile';
  static const String editProfile = 'Edit Profile';
  static const String edit = 'Edit';
  static const String editWorkDetails = 'Edit Work Details';
  static const String logout = 'Logout';
  static const String delete = 'Delete';
  static const String cancel = 'Cancel';
  static const String accept = 'Accept';
  static const String reject = 'Reject';
  static const String report = 'Report';
  static const String close = 'Close';
  static const String trackTask = 'Track Task';
  static const String pay = 'Pay';
  static const String areYouSureYouWantLogoutYourAccount = 'Are you sure you want to logout your account?';
  static const String areYouSureYouWantDeleteYourAccount =
      'Once you delete your account, there\'s no\ngetting it back. Make sure you want\nto do this.';
  static const String withdrawConformation = 'Are you sure you want to withdraw\nyour complaint? This action cannot\nbe undone.';
  static const String deletePhotograph = 'Are you sure you want to delete\nthis photograph? This action cannot\nbe undone.';
  static const String deleteNotification = 'Are you sure you want to clear\n all notifications? This action cannot\nbe undone.';
  static const String wallet = 'Wallet';
  static const String onlyForYou = 'Pre Launch Offer';
  static const String recharge = 'Recharge';
  static const String rechargeBalance = 'Recharge Balance';
  static const String rechargeHistory = "Recharge History";
  static const String rechargePlan = 'Recharge Plan';
  static const String myDocument = 'My Document';
  static const String complaints = 'Complaints';
  static const String referral = 'Referral';
  static const String becomeRider = 'Become a Rider';
  static const String settings = 'Settings';
  static const String howToUse = 'How to Use';
  static const String aboutUs = 'About Us';
  static const String faq = 'FAQ\'s';
  static const String privacyPolicy = 'Privacy Policy';
  static const String termsConditions = 'Terms & Conditions';
  static const String contactUs = 'Contact Us';
  static const String unauthorisedUser = 'Unauthorised User';
  static const String agreeToThe = 'I agree to the';
  static const String uploadProfilePicture = 'Upload Profile Picture';
  static const String currentLocation = 'Current Location';
  static const String beta = 'Beta';
  static const String beti = 'Beti';
  static const String createWork = 'Create Work';
  static const String editWork = 'Edit Work';
  static const String orWith = 'Or with';
  static const String or = 'Or';
  static const String google = 'Google';
  static const String apple = 'Apple';
  static const String deleteAccount = 'Delete Account';
  static const String transactions = 'Transactions';
  static const String transactionId = 'Transaction ID';
  static const String typeOfTransaction = 'Type of Transaction';
  static const String planName = 'Plan Name';
  static const String activePlan = 'Active Plan';
  static const String addMoney = 'Add Money';
  static const String walletBalance = 'Wallet Balance';
  static const String distanceAvailable = 'Available Distance';
  static const String timeAvailable = 'Available Time ';
  static const String taskAvailable = 'Available Task ';
  static const String bikeCharges = 'Bike Charges';
  static const String walkCharges = 'Walk Charges';
  static const String baseTask = 'Base Task';
  static const String baseTime = 'Base Time';
  static const String baseDistance = 'Base Distance';
  static const String time = 'Time';
  static const String km = 'KM';
  static const String mins = 'mins';
  static const String min = 'min';
  static const String mts = 'mts';

  //static const String hrs = 'hrs';
  //static const String hr = 'hr';
  static const String task = 'Task';
  static const String task2 = 'task';
  static const String tasks = 'tasks';
  static const String planId = 'Plan Id';
  static const String validity = 'Validity';
  static const String days = 'days';
  static const String day = 'day';
  static const String enterAmount = 'Enter Amount';
  static const String active = 'Active';
  static const String welcomeToYourBeta24App = 'Welcome to Your Beta24 App';
  static const String chooseYourBeta24BookingEasily = 'Choose Your Beta24 Booking Easily';
  static const String bookTaskAnytimeAnywhere = 'Book a Task Anytime, Anywhere!';
  static const String getStarted = 'Get Started';
  static const String enableLocationService = 'Enable Location Service';
  static const String enableLocationPermission = 'Enable Location Permission';
  static const String enableLocationServicesYourDeviceInside = 'Enable location services on your device inside';
  static const String privacy = 'Privacy';
  static const String locationServices = 'location services';
  static const String okGotIt = 'Ok, got it';
  static const String openSetting = 'Open Setting';
  static const String locationPermissionDescription = 'Enable location permission to fetch your current location';
  static const String searchPlace = 'Search place';
  static const String ourTeamWillBeContactYouWithin24 = 'Our team will be contact\nyou within 24 hrs.';
  static const String yourFeedbackHasBeenSubmittedSuccessfully = 'Your feedback has been\nsubmitted successfully';
  static const String setting = 'Setting';
  static const String yourReferralCode = 'Your referral code:';
  static const String copy = 'Copy';
  static const String opened = 'Opened';
  static const String shareYourReferralCodeWithYourFriends = 'Share your referral code with your\nfriends and get benefits.';
  static const String inviteFriends = 'Invite Friends';
  static const String noDataFound = 'No Data Found';
  static const String user = 'User';
  static const String rider = 'Rider';
  static const String title = 'Title';
  static const String description = 'Description';
  static const String callUs = 'Call Us';
  static const String emailUs = 'Email Us';

  static const String accountDeleted = 'Account Deleted';
  static const String approve = 'Approve';
  static const String taskDetails = 'Task Details';
  static const String viewOnMap = 'view on map';
  static const String estimationDetails = 'Estimation Details';
  static const String paymentDetails = 'Payment Details';
  static const String paymentRequired = 'Payment Required';
  static const String requiredBalance = 'Required Balance';
  static const String pin = 'Pin :';
  static const String estimatedTime = 'Estimated Time';
  static const String estimatedAmount = 'Estimated Amount';
  static const String totalAmount = 'Total Amount';
  static const String payableAmount = 'Payable Amount';
  static const String paidAmount = 'Paid Amount';
  static const String walletAmount = 'Wallet Amount';
  static const String gst = 'GST';
  static const String amount = 'Amount';
  static const String discount = 'Discount';
  static const String areYouSureYouWantMarkThisTaskAsDone = 'Are you sure you want to mark this\ntask as done?';
  static const String yes = 'Yes';
  static const String no = 'No';
  static const String pleaseMentionReasonForCancellingThisTask = 'Please mention a reason for cancelling this task';
  static const String mentionHereReasonWhyYouAreRejectingThisTask = 'Mention here a reason why you are rejecting this task.';
  static const String dateTime = 'Date/Time';
  static const String activeTaskTime = 'Active Task Time';
  static const String taskId = 'Task ID';
  static const String status = 'Status';
  static const String raiseComplaint = 'Raise Complaint';
  static const String rechargeNow = 'Recharge Now';
  static const String promoCode = 'Promo Code';
  static const String enterPromoCode = 'Enter promo code';
  static const String apply = 'Apply';
  static const String applyCode = 'Apply Code';
  static const String promoCodeApplied = 'Promo code Applied';
  static const String paymentSuccessful = 'Payment Successful';
  static const String withdrawal = 'Withdrawal';
  static const String photos = 'Photos';
  static const String addPhoto = 'Add Photo';
  static const String attachments = 'Attachments';
  static const String remark = 'Remark';
  static const String distance = 'Distance';
  static const String duration = 'Duration';
  static const String remove = 'Remove';
  static const String note = 'Note: ';
  static const String complaintAt = 'Complaint At : ';
  static const String resolvedAt = 'Resolved At : ';
  static const String itAllDependsOnTheTimeTheTaskCompleted = 'It all depends on the time and distance for the task completed.';
  static const String cancellationChargesMayApply = 'By continue, you are agree to pay cancellation charges.';
  static const String category = 'Category';
  static const String bike = 'Bike';
  static const String walk = 'Walk';
  static const String accountPrivacy = 'Account Privacy';
  static const String notificationSetting = 'Notification Setting';
  static const String mapSetting = 'Map Setting';
  static const String deleteMyAccount = 'Delete my account';
  static const String deleteMyAccountDesc = 'Why would you like to delete your account?';
  static const String iDoNotWantToUseBeta24Anymore = 'I don\'t want to use Beta24 anymore';
  static const String iAmUsingDifferentAccount = 'I am using a different account';
  static const String iMWorriedAboutMyPrivacy = 'I\'m worried about my privacy';
  static const String sendingMeTooManyEmailsNotifications = 'Sending me too many emails/notifications';
  static const String theAppIsNotWorkingProperly = 'The app is not working properly';
  static const String other = 'Other';
  static const String accountPrivacyAndPolicy = 'Account privacy and policy';
  static const String requestToDeleteAccount = 'Request to delete account';
  static const String requestToClosureOfYourAccount = 'Request to closure of your account';
  static const String applyPromoCode = 'Apply PromoCode';
  static const String hybrid = 'Hybrid';
  static const String terrain = 'Terrain';
  static const String packEndsOn = 'Pack ends on ';
  static const String callNow = 'Call Now';
  static const String rate = 'Rate';
  static const String areYouSure = 'Are you sure?';
  static const String enterYourReviewHere = 'Enter your review here';
  static const String successfullyPaid = 'Successfully paid';
  static const String clearNotification = 'Clear Notifications';
  static const String hereTheBreakdownYourRechargePlanCost =
      'Here\'s the breakdown of your recharge plan cost, including GST and the total payable amount.';
  static const String insufficientBalance = 'You do not have sufficient balance to assign task. Please recharge and Enjoy Beta24.';
  static const String activeTaskAlert =
      'You already have an active task in progress. Feel free to assign any new tasks to your designated Beta24 Assistant.';
  static const String selectThePlanYouWishAddThisTopUpAndContinueEnhancingYourExperience =
      'Select the plan you wish to add this top-up to and continue enhancing your experience';
  static const String selectTheAccountYouWishToContinue = 'Select the account you wish to continue';
  static const String selectTheTaskYouWishToCancel = 'Select the task you wish to cancel';
  static const String insufficientBalanceForApprove =
      'For approving this task you do not have sufficient balance. Please recharge your account and continue.';
  static const String yourActivePlanIsDisplayedHere = 'Your active plan is displayed here.';
  static const String needActiveBikePlanToTopUp =
      'Oops! You need an active Bike Plan to top-up. Purchase a Bike Magic Plan to unlock this feature.';
  static const String needToAddPlanToTopUp =
      'Oops! You haven\'t added anything to your top-up plan yet. Please make a selection and proceed.';
  static const String needActiveWalkPlanToTopUp =
      'Oops! You need an active Walk Plan to top-up. Purchase a Walk Magic Plan to unlock this feature.';
  static const String notificationSettingDesc =
      'We may still send you important about your account of outside of your notification settings.';
  static const String mapSettingDesc = 'Please select your preferred map type.';
  static const String somethingWentWrongPleaseTryLater = 'Something went wrong. Please try later.';
  static const String getToKnowYour = 'Get to know your ';
  static const String availableTask = 'Available Task';
  static const String availableTime = 'Available Time';
  static const String availableDistance = 'Available Dist.';
  static const String estimatedDistance = 'Estimated Dist.';
  static const String yourBalance = 'Your Balance';
  static const String viewDetails = 'View Details';
  static const String location = 'Location';
  static const String dropAddress = 'Drop Address';
  static const String baseCharges = 'Base Charges';
  static const String typeMessage = 'Type Message';
  static const String noComplaintYet = 'No Complaint Yet !!';
  static const String fullNameCanotbeEmpty = 'Full name can\'t be empty';
  static const String nameMustContainAtLeast3letters = 'Name must contain at least 3 letters';
  static const String dateOfBirthCantBeEmpty = 'Date of birth can\'t be empty';
  static const String emailAddressCantBeEmpty = 'Email address can\'t be empty';
  static const String emailAddressIsInvalid = 'Email address is invalid';
  static const String genderCantBeEmpty = 'Gender can\'t be empty';
  static const String addressCantBeEmpty = 'Address can\'t be empty';
  static const String stateCantBeEmpty = 'State can\'t be empty';
  static const String cityCantBeEmpty = 'City can\'t be empty';
  static const String failedToFetchUserLocation = 'Failed to fetch user location.';
  static const String settingUpdateSuccessfully = 'Setting update successfully';
  static const String peaseCheckIAgreeToThePrivacyPolicyTermsConditions =
      "Please check \"I agree to the Privacy Policy, Terms & Conditions\"";
  static const String pressBackAgainToLeave = 'Press back again to leave';
  static const String recommended = 'Recommended';
  static const String magicPack = 'Magic Pack';
  static const String topupTask = 'Topup (Task)';
  static const String topupTime = 'Topup (Time)';
  static const String topupDistance = 'Topup (Distance)';
  static const String topUpPlan = 'Top-Up Plan';
  static const String yourRecommendationCodeIs =
      'Hello there! Are You ready to make life easier? Download the Beta24 app now and get a special bonus when you sign up using my referral code:';
  static const String yourRecommendationCodeIs2 = 'Download Now:';
  static const String riderApp = 'Rider App - ';
  static const String userApp = 'User App –';
  static const String your = 'Your';
  static const String assistant = 'Assistant';
  static const String gallery = 'Gallery';
  static const String camera = 'Camera';
  static const String off = 'OFF';
  static const String comingSoon = 'Coming Soon';
  static const String writeFeedback = 'Write Feedback';
  static const String contactSupport = 'Contact Support';
  static const String personalAssistant = 'Personal Assistant';
  static const String dear = 'Dear';
  static const String finishTask = 'Finish Task';
  static const String rechargehistory = 'Recharge History';
  static const String taskDescription = 'Task Description';
  static const String addTaskDescription = 'Add task description';
  static const String buildingNoApartmentNoFloorNo = 'Building No. /Apartment No. /Floor No.';
  static const String landmark = 'Landmark';
  static const String myCurrentLocation = 'My Current Location';
  static const String copyAboveDropLocation = 'Copy above drop location';
  static const String copyAbovePickLocation = 'Copy above pick location';
  static const String pinRequired = 'Pin Required';
  static const String deleteTask = 'Delete Task';
  static const String plusAddTask = '+ Add Task';
  static const String sendForApproval = "Send for Approval";
  static const String workDetails = 'Work Details';
  static const String finishTaskDesc = 'You have a work waiting for completion.\nWould you like to finish it now?';
  static const String baseChargeNote =
      'The charges mentioned above are the base charges for any task.\nAdditional distance, time, or extra tasks may increase the final charges. All charges are displayed upfront to ensure complete transparency.';
  static const String accountPrivacyDesc =
      'We i.e. \"${Constants.companyName}\" (\"Company\"), are committed to protecting the privacy and security of your personal information. Your privacy is important to us and maintaining your trust is paramount.';

  //Task Status
  static const String created = "Created"; //0
  static const String waitingForApproval = 'Approval Requested'; //1
  static const String inTransit = 'Active Task'; //2
  static const String payment = 'Payment'; //3
  static const String completed = 'Completed'; //4
  static const String cancelled = 'Cancelled'; //5

  //Complaint Status
  static const String inProgress = 'In Progress'; //1
  static const String resolved = 'Resolved'; //2
  static const String withdraw = 'Withdraw'; //3

  // Congratulations Popup
  static const String congratulations = "Congratulations!";
  static const String firstTaskFree = "First task FREE for both Walk & Ride";
  static const String taskValue = "01";
  static const String timeValue = "15 mins";
  static const String bikeDistanceValue = "2.5 KM";
  static const String walkDistanceValue = "1.5 KM";

  // Recharge Popup
  static const String getFreeRecharge = "Get Free Recharge";
  static const String claimOfferDescription = "Walk & Bike, Beta24 makes your first move free";
  static const String claimNow = "Claim Now";
  static const String freeRechargeForBothWalkRide = "FREE recharge for both Walk & Bike";
  static const String skipNow = "Skip Now >";
}
